### ISSUE TITLE
Test case v17 generates expected error, update needed

### ISSUE THREAD

**Issue by ASinanSaglam** [RuleWorld/nfsim#27]
[Test case 17](https://github.com/RuleWorld/nfsim/blob/master/validate/basicModels/v17.bngl) generates an expected error and needs updating. 

Observable of the form
```
Molecules Rpattern L(s!2,s!1).R(s!2,s!3).L(s!3,s!4)
```
is not allowed in NFsim due to dangling edges.

**Comment by aadibiasi** [comment]
This was fixed, closing the issue.
